#!/usr/bin/python
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free  Software Foundation; either version 2 of the License, or
# (at your option)  any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301 USA.

import logging
import optparse
import sys

import scratchlivedb

log = logging.getLogger("scratchlivedb")
log.setLevel(logging.DEBUG)


######################
# Functional helpers #
######################

def setup_logging(debug):
    handler = logging.StreamHandler(sys.stderr)
    if debug:
        handler.setLevel(logging.DEBUG)
        formatter = logging.Formatter(
            "%(levelname)-6s (%(module)s:%(lineno)d): %(message)s")
    else:
        handler.setLevel(logging.WARN)
        formatter = logging.Formatter("%(levelname)-6s %(message)s")

    handler.setFormatter(formatter)
    log.addHandler(handler)

    log.debug("Launched with command line: %s", " ".join(sys.argv))


###################
# main() handling #
###################

def parse_options():
    parser = optparse.OptionParser(usage="%prog DBFILE",
                description="Tool for manipulating Scratch Live DB files")

    parser.add_option("--debug", action="store_true",
                      help="Print debug output to stderr")

    options, args = parser.parse_args()
    if len(args) < 1:
        parser.error("Must specify a db file")
    if len(args) > 1:
        parser.error("Unused positional args %s" % args[1:])

    return options, args[0]


def main():
    options, dbfile = parse_options()
    setup_logging(options.debug)

    print "Parsing database: %s" % dbfile
    scratchlivedb.ScratchDatabase(dbfile)

    return 0


if __name__ == '__main__':
    sys.exit(main())
