#!/usr/bin/python
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free  Software Foundation; either version 2 of the License, or
# (at your option)  any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301 USA.

import logging
import optparse
import os
import sys

import scratchlivedb

log = logging.getLogger("scratchlivedb")
log.setLevel(logging.DEBUG)


###################
# Utility methods #
###################

def fail(msg):
    print >> sys.stderr, "ERROR: %s" % msg
    sys.exit(1)


######################
# Functional helpers #
######################

def setup_logging(debug):
    handler = logging.StreamHandler(sys.stderr)
    if debug:
        handler.setLevel(logging.DEBUG)
        formatter = logging.Formatter(
            "%(levelname)-6s (%(module)s:%(lineno)d): %(message)s")
    else:
        handler.setLevel(logging.WARN)
        formatter = logging.Formatter("%(levelname)-6s %(message)s")

    handler.setFormatter(formatter)
    log.addHandler(handler)

    log.debug("Launched with command line: %s", " ".join(sys.argv))


###################
# main() handling #
###################

def parse_options():
    parser = optparse.OptionParser(usage="%prog DBFILE",
                description="Tool for manipulating Scratch Live DB files")

    parser.add_option("--debug", action="store_true",
                      help="Print debug output to stderr")

    actg = optparse.OptionGroup(parser, "Actions")
    actg.add_option("--sync-rhythmbox", action="store_true",
                    help=("Sync DB with rhythmbox library."
                          "Only scratch DB is altered. Currently this only "
                          "removes missing files and syncs timeadded value."))
    actg.add_option("--rhythmdb", help=optparse.SUPPRESS_HELP)

    actg.add_option("--outfile", default="./out.db",
                    help="New DB file to write (default=%default)")
    actg.add_option("--dry-run", action="store_true",
                    help="Don't save any changes")
    parser.add_option_group(actg)

    options, args = parser.parse_args()
    if len(args) < 1:
        parser.error("Must specify a db file")
    if len(args) > 1:
        parser.error("Unused positional args %s" % args[1:])

    return options, args[0]


def main():
    options, dbfile = parse_options()
    setup_logging(options.debug)

    if os.path.exists(options.outfile):
        fail("outfile=%s already exists" % options.outfile)

    print "Parsing database: %s" % dbfile
    db = scratchlivedb.ScratchDatabase(dbfile)

    sync = None
    if options.sync_rhythmbox:
        print "Parsing rhythmbox DB"
        sync = scratchlivedb.SyncRhythmbox(options.rhythmdb)

    if sync:
        sync.sync(db)
    else:
        print "No action selected, nothing to do."
        return 0

    print "Writing %s%s" % (options.outfile, options.dry_run and
                            " (dry)" or "")
    if not options.dry_run:
        file(options.outfile, "w").write(db.get_final_content())

    return 0


if __name__ == '__main__':
    sys.exit(main())
