#!/usr/bin/python

import logging
import optparse
import sys

import scratchlivedb

log = logging.getLogger("scratchlivedb")
log.setLevel(logging.DEBUG)


###################
# Utility methods #
###################

def fail(msg):
    print >> sys.stderr, "ERROR: %s" % msg
    sys.exit(1)


######################
# Functional helpers #
######################

def setup_logging(debug):
    handler = logging.StreamHandler(sys.stderr)
    if debug:
        handler.setLevel(logging.DEBUG)
        formatter = logging.Formatter(
            "%(levelname)-6s (%(module)s:%(lineno)d): %(message)s")
    else:
        handler.setLevel(logging.WARN)
        formatter = logging.Formatter("%(levelname)-6s %(message)s")

    handler.setFormatter(formatter)
    log.addHandler(handler)

    log.debug("Launched with command line: %s", " ".join(sys.argv))


###################
# main() handling #
###################

def parse_options():
    desc = "Command line tool for interacting with scratchlive databases"
    parser = optparse.OptionParser(usage="%prog DBFILE", description=desc)

    parser.add_option("--debug", action="store_true",
                      help="Print debug output to stderr")

    actg = optparse.OptionGroup(parser, "Actions")
    parser.add_option_group(actg)

    options, args = parser.parse_args()
    if len(args) < 1:
        parser.error("Must specify a db file")
    if len(args) > 1:
        parser.error("Unused positional args %s" % args[1:])

    return options, args[0]


def main():
    options, dbfile = parse_options()
    setup_logging(options.debug)

    print "Parsing database: %s" % dbfile
    scratchlivedb.ScratchDatabase(dbfile)

    print "No action selected, nothing to do."
    return 0


if __name__ == '__main__':
    sys.exit(main())
